### ISSUE TITLE
Change isilon to files.brown.edu

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-status-frontend#9]
Hello! 

I'm wondering if we could change the `isilon` badge on the app to read `files.brown.edu`. The reason I ask is that "Isilon" is just the name of the physical storage appliance. It's not going to be obvious to most folks; the users probably know it as "files.brown.edu" or may "campus file storage".

Would re-naming be a straightforward thing to do? It looks like the code is just pulling the repo names for the badge—so maybe we just re-name that repo. Is that right?

As always, thank you!!

**Comment by fernandogelin** [comment]
Done. @paulstey  For reference all we need to do is rename the repo in the `ccv-status` organization
